# App set up
mode: debug  # debug, devel or prod
server: 127.0.0.1
port: 8050
core_path: /flex-fcst-maproom
admin_path: /flex-fcst-maproom-admin
tile_path: /flex-fcst-maproom-tiles
support_email: help@iri.columbia.edu
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP

# Forecast options
forecast_path: /data/xchourio/data/BMD-S2S-Data-Example/output
y_transform: true
start_regex: \w{3}-\w{1,2}-\w{4}
start_format_in: '%b-%d-%Y'
start_format_out: '%b-%-d-%Y'
forecast_mu_file_pattern: CFSv2_SubXPRCP_CCAFCST_mu_Apr_*.txt
forecast_var_file_pattern: CFSv2_SubXPRCP_CCAFCST_var_Apr_*.txt
obs_file_pattern: CFSv2_SubXPRCP_CCAFCST_obs_Apr_*.txt
hcst_file_pattern: CFSv2_SubXPRCP_CCAFCST_xvPr_Apr_*.txt
variable: Precipitation Anomaly

#S,L, target dates options
target_period_length: 7
time_units: days

# Viz' set up
zoom: 7
