# Senegal
logo: anacimLogo.jpg
institution: ANACIM
zoom: 7

datasets:
    shapes_adm:
        - name: Pays
          color: black
          sql: select id_0 as key, name_0 as label, ST_AsBinary(the_geom) as the_geom
                  from sen_adm0
          is_checked: False
        - name: Régions
          color: black
          sql: select id_1 as key, name_1 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm1
          is_checked: True
        - name: Départements
          color: grey
          sql: select id_2 as key, name_2 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm2
          is_checked: True
        - name: Arrondissements
          color: black
          sql: select id_3 as key, name_3 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm3
          is_checked: False
        - name: Commune
          color: grey
          sql: select id_4 as key, name_4 as label, ST_AsBinary(the_geom) as the_geom
              from sen_adm4
          is_checked: False

    # Daily ENACTS Zarr conversion
    daily:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 592
            Y: 31
            X: 29
        zarr_path: /data/aaron/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - ANACIM/anacim_v3/ALL_block2/rr_mrg_daily/
                - null
                - precip
            tmax: 
                - ANACIM/anacim_v3/ALL_block2/tx_mrg_daily/
                - null
                - temp
            tmin: 
                - ANACIM/anacim_v3/ALL_block2/tn_mrg_daily/
                - null
                - temp

    # Dekadal ENACTS Zarr conversion
    #dekadal: # Same-same as daily

maprooms:
    # Onset
    onset:

        # Onset_and_Cessation
        default_search_month: May
        default_running_days: 3
        default_min_rainy_days: 1
        ison_cess_date_hist: False
        map_text:
            length_mean:
                map_max: 180
            length_stddev:
                map_max: 40

    # Water Balance Monitoring
    wat_bal_monit:

        planting_month: Jun
        crop_name: Rice
        kc_v: [0, 0, 1.1, 1.1, 0]
        kc_l: [3, 27, 45, 60]
        taw_file: /data/remic/mydatafiles/soilgrids/Senegal/GYGA_ERZD_wat_cap_abs_anacim_enacts3.nc
        taw_max: 136

