# Kenya
zoom: 6
map_center: [-1.2921, 36.8219]

datasets:
    shapes_adm: 
        - name: National
          color: black
          sql: select gid as key, 'Kenya' as label, ST_AsBinary(the_geom) as the_geom from kenya_territory
          is_checked: True
        - name: Counties
          color: black
          sql: select gid as key, counties as label, ST_AsBinary(the_geom) as the_geom from kenya_counties_t
          is_checked: True
        - name: Sub-counties
          color: grey
          sql: select gid as key, admin2 as label, ST_AsBinary(the_geom) as the_geom from kenya_sub_counties
          is_checked: False
        - name: Wards
          color: grey
          sql: select gid as key, (name_3 || ', ' || name_2 || ', ' || name_1) as label, ST_AsBinary(the_geom) as the_geom from ken_adm3
          is_checked: False

    data_dir: /data/datalib/data/zarr/enacts/v3/dekadal

    chunks:
        T: 578
        Y: 27
        X: 25

maprooms: 
    # Climate Analysis - Monthly
    monthly:

        vars:
            Rainfall:
                max: 500
            Minimum Temperature:
                min: -5
                max: 40
            Maximum Temperature:
                min: -5
                max: 40
    flex_fcst: null
    onset: null
    wat_bal: null
