# Mali
logo: mali.gif
institution: MaliMétéo
zoom: 5

datasets:
    shapes_adm:
        - name: National
          color: black
          sql: select 0 as key, 'Mali' as label,
              ST_AsBinary(ST_Simplify(ST_Union(the_geom), .01)) as the_geom
              from mal_level_1
          is_checked: True
        - name: Provinces
          color: black
          sql: select gid as key, caption as label, ST_AsBinary(the_geom) as the_geom
                      from mal_level_1
          is_checked: True
        - name: Districts
          color: grey
          sql: select gid as key, label, ST_AsBinary(the_geom) as the_geom
                    from mal_level_2
          is_checked: True

    # Daily ENACTS Zarr conversion
    daily:
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 600
            Y: 23
            X: 24
        zarr_path: /data/remic/mydatafiles/
        vars:
           #var name in file name:
           #    - input file path relative to nc_path
           #    - output file path relative to zarr_path (set to null if same as input file path)
           #    - var name def in file
            precip: 
                - MaliMeteo/ENACTS/ALL/mrg_precip_daily/
                - null
                - precip
            tmax: 
                - MaliMeteo/ENACTS/ALL/mrg_tmax_daily_s/
                - null
                - temp
            tmin: 
                - MaliMeteo/ENACTS/ALL/mrg_tmin_daily_s/
                - null
                - temp

    # Dekadal ENACTS Zarr conversion
    dekadal: 
        nc_path: /Data/data23/
        zarr_resolution: null #set to null for no regridding
        chunks: #consider changing chunk sizes if regridding
            T: 360
            Y: 23
            X: 24
        zarr_path: /data/remic/mydatafiles/
        vars:
            precip:
                - MaliMeteo/ENACTS/ALL/mrg_precip_dekad/
                - null
                - precip
            tmax:
                - MaliMeteo/ENACTS/ALL/mrg_tmax_dekad/
                - null
                - temp
            tmin:
                - MaliMeteo/ENACTS/ALL/mrg_tmin_dekad/
                - null
                - temp

maprooms:
    # Climate Analysis -- Monthly
    monthly:

        vars:
            Rainfall:
                max: 450
            Minimum Temperature:
                min: 8
                max: 50
            Maximum Temperature:
                min: 8
                max: 50

    # Onset
    onset:

        # Onset_and_Cessation
        default_search_month: Jun
        default_running_days: 5
        default_min_rainy_days: 3
        ison_cess_date_hist: True
        map_text:
            length_mean:
                map_max: 180
            length_stddev:
                map_max: 40

    flex_fcst: null
    wat_bal: null
